permissions:
  - '*'
sessions:
  session:
    useTLS: false
    redirect: true


jobs:
  preprocessing:
    steps:
      - name: Clone workflow code to resource
        env:
          sshcmd: ssh -o StrictHostKeyChecking=no ${{ inputs.pwrl_host.resource.ip }}
        run: |
          echo $PWD
      - name: Check and install OpenMPI
        run: |
          echo Checking for MPI...
      - name: Check and install Conda env
        run: |
          echo CHecking for Conda env...

  run_workflow:
    needs:
       - preprocessing
    steps:
       - name: Launch workflow
         env:
          sshcmd: ssh -o StrictHostKeyChecking=no ${{ inputs.pwrl_host.resource.ip }}
        run: |
          target_hostname=$(${sshcmd} hostname)
          echo "target_hostname=${target_hostname}"
          echo ${{ inputs. }}

'on':
  execute:
    inputs:
      pwrl_host:
        type: group
        label: TIEGCM
        items:
          resource:
            type: compute-clusters
            label: Workflow host
            include-workspace: false
            tooltip: Resource to host the workflow
        collapsed: false
      tiegcm_inputs:
        type: group
        label: TIEGCM Settings
        items:
          warm_start:
            label: Warm start?
            type: boolean
            default: true
            tooltip: Select Yes for warm start, no for cold start.
          mlflow_install_cmd:
            label: Command to Install MLflow
            type: string
            default: pip3 install mlflow
          n_ens:
            label: Number of ensemble members
            type: integer
            default: 10
            tooltip: Enter the integer number of TIEGCM ensemble members.
