permissions:
  - '*'

jobs:
  preprocessing:
    steps:
      - name: Clone workflow code to resource
        env:
          sshcmd: ssh -o StrictHostKeyChecking=no ${{ inputs.pwrl_host.resource.ip }}
        run: |
          $(${sshcmd} "mkdir -p ${{inputs.tiegcm.workdir_root}}; cd ${{inputs.tiegcm.workdir_root}}; git clone https://github.com/parallelworks/tiegcm-digital-twin; cd tiegcm-digital-twin; git checkout sfg-fix-create_ens_dirs;")
      - name: Check and install OpenMPI
        env:
          sshcmd: ssh -o StrictHostKeyChecking=no ${{ inputs.pwrl_host.resource.ip }}
        run: |
          echo Checking for MPI...
          $(${sshcmd} "cd ${{inputs.tiegcm.workdir_root}}/tiegcm-digital-twin; ./install_openmpi.sh 1>install_openmpi.stdout 2>install_openmpi.stderr")
      - name: Check and install Conda env
        env:
          sshcmd: ssh -o StrictHostKeyChecking=no ${{ inputs.pwrl_host.resource.ip }}
        run: |
          echo Checking for Conda env...
          $(${sshcmd} "cd ${{inputs.tiegcm.workdir_root}}/tiegcm-digital-twin; ./install_conda.sh /home/$USER/pw/software/.miniconda3 parsl")
  run_workflow:
    needs:
      - preprocessing
    steps:
      - name: Launch workflow
        env:
          sshcmd: ssh -o StrictHostKeyChecking=no ${{ inputs.pwrl_host.resource.ip }}
        run: |
          target_hostname=$(${sshcmd} hostname)
          echo "target_hostname=${target_hostname}"
          echo ${{ inputs.tiegcm.start_type }}
          echo ${{ inputs.tiegcm.n_ens}}
'on':
  execute:
    inputs:
      pwrl_host:
        type: group
        label: TIEGCM
        items:
          resource:
            type: compute-clusters
            label: Workflow host
            include-workspace: false
            tooltip: Resource to host the workflow
        collapsed: false
      tiegcm:
        type: group
        label: TIEGCM Settings
        items:
          workdir_root:
            label: Main working directory for everything
            type: string
            default: /home/${USER}/pw/jobs/
            tooltip: Root directory for where workflow lives and runs
          start_type:
            label: Start type
            type: string
            default: warm
            tooltip: Select from 'warm' or 'cold' starts
          n_ens:
            label: Number of ensemble members
            type: number
            default: 10
            tooltip: Enter the integer number of TIEGCM ensemble members.


